export const USER_REQUIEST = 'USER_REQUIEST';
export const USER_SUCCCESS = 'USER_SUCCCESS';
export const USER_LOGOUT_SUCCCESS = 'USER_LOGOUT_SUCCCESS';

export const USER_FAIL = 'USER_FAIL';
export const USER_GETME_REQUIEST = 'USER_GETME_REQUIEST';
export const USER_GETME_SUCCCESS = 'USER_GETME_SUCCCESS';
export const USER_GETME_FAIL = 'USER_GETME_FAIL';


export const USER_REGISTER_REQUIEST = "USER_REGISTER_REQUIEST";
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS";
export const USER_REGISTER_FAIL = "UREGISTER_SER_FAIL";

export const ACCOUNT_REQUIEST = "ACCOUNT_REQUIEST";
export const ACCOUNT_SUCCCESS = "ACCOUNT_SUCCCESS";
export const ACCOUNT_FAIL = "ACCOUNT_FAIL";

export const ACCOUNT_ADD_REQUIEST = "ACCOUNT_ADD_REQUIEST";
export const ACCOUNT_ADD_SUCCESS = "ACCOUNT_ADD_SUCCESS";
export const ACCOUNT_ADD_FAIL = "ACCOUNT_ADD_FAIL";

export const ACTIVITY_REQUIEST = "ACTIVITY_REQUIEST";
export const ACTIVITY_SUCCESS = "ACTIVITY_SUCCESS";
export const ACTIVITY_FAIL = "ACTIVITY_FAIL";

export const ALL_USER_REQUIEST = "ALL_USER_REQUIEST";
export const ALL_USER_SUCCESS = "ALL_USER_SUCCESS";
export const ALL_USER_FAIL = "ALL_USER_FAIL";

export const GROUP_CREATE_REQUEST = "GROUP_CREATE_REQUEST";
export const GROUP_CREATE_SUCCESS = "GROUP_CREATE_SUCCESS";
export const GROUP_CREATE_FAIL = "GROUP_CREATE_FAIL";

export const GET_SOURCE_REQUEST = "GET_SOURCE_REQUEST";
export const GET_SOURCE_RESPONSE = "GET_SOURCE_RESPONSE";
export const GET_SOURCE_FAIL = "GET_SOURCE_FAIL";

export const GET_EXPENDTYPE_REQUEST = "GET_EXPENDTYPE_REQUEST";
export const GET_EXPENDTYPE_RESPONSE = "GET_EXPENDTYPE_RESPONSE";
export const GET_EXPENDTYPE_FAIL = "GET_EXPENDTYPE_FAIL";

export const GET_MEMBER_REQUEST = "GET_MEMBER_REQUEST";
export const GET_MEMBER_RESPONSE = "GET_MEMBER_RESPONSE";
export const GET_MEMBER_FAIL = "GET_MEMBER_FAIL";

export const GET_ANALYSIS_REQUEST = "GET_ANALYSIS_REQUEST";
export const GET_ANALYSIS_SUCCESS = "GET_ANALYSIS_SUCCESS";
export const GET_ANALYSIS_FAIL = "GET_ANALYSIS_FAIL";

export const GET_ANALYSISEXPENDTYPE_REQUEST = "GET_ANALYSISEXPENDTYPE_REQUEST";
export const GET_ANALYSISEXPENDTYPE_SUCCESS = "GET_ANALYSISEXPENDTYPE_SUCCESS";
export const GET_ANALYSISEXPENDTYPE_FAIL = "GET_ANALYSISEXPENDTYPE_FAIL";

export const GET_ANALYSISSOURCE_REQUEST = "GET_ANALYSISSOURCE_REQUEST";
export const GET_ANALYSISSOURCE_SUCCESS = "GET_ANALYSISSOURCE_SUCCESS";
export const GET_ANALYSISSOURCE_FAIL = "GET_ANALYSISSOURCE_FAIL";

export const GET_ANALYSISEARNBY_REQUEST = "GET_ANALYSISEARNBY_REQUEST";
export const GET_ANALYSISEARNBY_SUCCESS = "GET_ANALYSISEARNBY_SUCCESS";
export const GET_ANALYSISEARNBY_FAIL = "GET_ANALYSISEARNBY_FAIL";

export const GET_ANALYSISEXPENDBY_REQUEST = "GET_ANALYSISEXPENDBY_REQUEST";
export const GET_ANALYSISEXPENDBY_SUCCESS = "GET_ANALYSISEXPENDBY_SUCCESS";
export const GET_ANALYSISEXPENDBY_FAIL = "GET_ANALYSISEXPENDBY_FAIL";
